### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/ParrotDroneAltitudeControlROS#1]
Hello @eduardorasgado  , Im a Graphic Designer that likes to contribute to open source projects, can you tell me more about ParrotDroneAltitudeControlIROS? 
Im a Drone enthusiastic so I would like to get more informations about this project, so if you want it will be a pleasure to me to design a logo for this project.

Do you have something on your mind for the logo?

Greetings.

**Comment by eduardorasgado** [comment]
Do it dude.This is just a light functional project but I plan to create a cool product in a future. And I will add you if your work deserves. Something in mind: simplistic and futuristic, something flat maybe.

**Comment by eduardorasgado** [comment]
Thanks for your interest.

**Comment by zuurw** [comment]
Hi @eduardorasgado, I create this design for this project, the concept that used the word parrot and drone, so I created a parrot in which the wings create a drone helix the curved lines on the tops of the wings intend to recreate the movement of the drone's helix.

I do not know if you like it if not just tell me, that I create other design.

Cheers.

![parrot drone](https://user-images.githubusercontent.com/40801473/42290204-afdeb122-7fbb-11e8-9c57-a012f919b720.png)

**Comment by eduardorasgado** [comment]
Cool bro. Thanks, I will add one to the Parrot project.

**Comment by zuurw** [comment]
Hi, Im happy that you like it, I will make a Pull request with this files, what colors do you want? 

Greetings!

**Comment by eduardorasgado** [comment]
Do it bruh, pull the big logo(there are two identical logo ahead, i mean that logo), the first one in the picture. Thanks for your collaboration.

**Comment by zuurw** [comment]
Ok, for the one color version, I will send you the black and white version.

Greetings!

**Comment by eduardorasgado** [comment]
Sure, go ahead!

**Comment by zuurw** [comment]
Hi @eduardorasgado, thanks for merged the PR.

I saw that you have a lot of projects, can I make a logo for this projects too?

- spheroRobotMazeSolver1
- indecisionApp
- recordariumApp
- bb8_moving_squareROS
- Robotics-ColumbiaX-Project3
- IRI_WAM_robot_unit_3_RobotIgniteAka
- kobuki_rbot_controls
- cambioORG

It will be a pleasure to me to work in this projects, so if you want just say it.

Best Regards!

**Comment by eduardorasgado** [comment]
What's up bro! For sure. Feel free to work on those projects. I will be opened for all the supporting people can give the projects. 

Just why dont you just change cambioORG and IndecisionApp for another repo, i have not started both neither yet. Why dont you choose spheroRobotMazeSolver1, SDC_3D_Simulator or despega-CMS instead. This last is a content management system for creating websites, still in progress but i have been working hard on this one. 

Here the links:
https://github.com/eduardorasgado/despega-CMS
https://github.com/eduardorasgado/SDC_3D_Simulator
https://github.com/eduardorasgado/spheroRobotMazeSolver1

I really appreciate your interest.

Cheers bro and thank you!

**Comment by zuurw** [comment]
Hi @eduardorasgado , can I open a issue in this 3 projects? 
Who is going to be the 1st? I like specialy this one spheroRobotMazeSolver1.

Cheers!

**Comment by eduardorasgado** [comment]
Yes, do it dude. Open the project you want first, feel free to choose. Thanks bro!
